# PhonePe Automation Project

## Notebook 2: Generate Daily Data

### Objective
Generate 50 realistic PhonePe transactions daily based on the existing dataset.

### Input
Original PhonePe Dataset

### Output
Daily Generated Dataset (50 Rows)

# Extract Existing Values in a way we can easily generate data randomly

In [18]:
import pandas as pd
import random
from datetime import datetime
import random
import string

In [2]:
df = pd.read_excel("../data/raw/phonepe_dataset.xlsx")

In [3]:
df.head()

,Transaction ID,Amount,User ID,Service,Service Type,Payment_Status,Reason,Date
0,RCG_0C338474B366,926.59,PP0021371,Recharge_Bills,FASTag Recharge,Successful,Successful,09-06-2024
1,RCG_6B3B86B07A76,1211.64,PP0002388,Recharge_Bills,DTH,Successful,Successful,04-08-2024
2,RCG_767822392A0E,746.27,PP1101831,Recharge_Bills,Cable TV,Successful,Successful,19-02-2024
3,RCG_527E6AC74B11,1319.89,PP0033099,NaN,Mobile Recharge,Successful,Successful,22-12-2024
4,RCG_6B50A8C694E1,112.44,PP1059869,Recharge_Bills,Cable TV,Successful,Successful,07-09-2024

In [4]:
services = df["Service"].dropna().unique().tolist()

In [5]:
service_types = df["Service Type"].dropna().unique().tolist()

In [7]:
payment_status = df["Payment_Status"].dropna().unique().tolist()

In [8]:
amount_min = int(df["Amount"].min())

In [9]:
amount_max = int(df["Amount"].max())

In [13]:
reasons = df["Reason"].dropna().unique().tolist()

In [15]:
print(services)
print(service_types)
print(payment_status)
print(reasons)

['Recharge_Bills']
['FASTag Recharge', 'DTH', 'Cable TV', 'Mobile Recharge', 'FASTag Recharge ', 'Mobile Recharge ', 'DTH ', 'Cable TV ', 'nan ']
['Successful', 'Failed']
['Successful', 'Insufficient amount', 'Wrong PIN', 'Server error']

# Generate 50 Transactions

In [21]:
new_data = []

today = datetime.today().strftime("%d-%m-%Y")

for i in range(50):

    transaction_id = "RCG_" + ''.join(random.choices(string.ascii_uppercase + string.digits, k=13))

    user_id = "PP" + str(random.randint(1000000, 9999999))

    service = random.choice(services)

    service_type = random.choice(service_types)

    amount = round(random.uniform(amount_min, amount_max),2)

    status = random.choices(
        ["Success","Failed"],
        weights=[90,10]
    )[0]

    if status=="Success":
        reason="Success"
    else:
        reason=random.choice([
            "Network Error",
            "Server Error",
            "Insufficient Balance"
        ])

    new_data.append([
        transaction_id,
        amount,
        user_id,
        service,
        service_type,
        status,
        reason,
        today
    ])

# DataFrame

In [24]:
daily_df = pd.DataFrame(
    new_data,
    columns=df.columns
)

daily_df.head()

,Transaction ID,Amount,User ID,Service,Service Type,Payment_Status,Reason,Date
0,RCG_ET844AJ87WMUX,777.19,PP3633125,Recharge_Bills,DTH,Success,Success,19-07-2026
1,RCG_6MR7CF7Z6L2MG,280.74,PP6687550,Recharge_Bills,FASTag Recharge,Failed,Insufficient Balance,19-07-2026
2,RCG_VV5RPY9Z3UWMA,900.17,PP3744534,Recharge_Bills,DTH,Success,Success,19-07-2026
3,RCG_8VNHQJM46SDHL,917.41,PP2459904,Recharge_Bills,DTH,Success,Success,19-07-2026
4,RCG_3AVDGPSBDOY0C,646.65,PP3537779,Recharge_Bills,DTH,Success,Success,19-07-2026

# Save file

In [26]:
file_name = f"../data/generated/daily_{today}.csv"

daily_df.to_csv(file_name,index=False)

print("50 Daily Transactions Generated Successfully")

50 Daily Transactions Generated Successfully