# In this notebook we will clean the master_dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../data/processed/master_raw_dataset.csv")

In [3]:
df.head()

,Transaction ID,Amount,User ID,Service,Service Type,Payment_Status,Reason,Date
0,RCG_0C338474B366,926.59,PP0021371,Recharge_Bills,FASTag Recharge,Successful,Successful,09-06-2024
1,RCG_6B3B86B07A76,1211.64,PP0002388,Recharge_Bills,DTH,Successful,Successful,04-08-2024
2,RCG_767822392A0E,746.27,PP1101831,Recharge_Bills,Cable TV,Successful,Successful,19-02-2024
3,RCG_527E6AC74B11,1319.89,PP0033099,NaN,Mobile Recharge,Successful,Successful,22-12-2024
4,RCG_6B50A8C694E1,112.44,PP1059869,Recharge_Bills,Cable TV,Successful,Successful,07-09-2024

In [4]:
df.tail()

,Transaction ID,Amount,User ID,Service,Service Type,Payment_Status,Reason,Date
2095,RCG_408JTREE6EHCX,755.39,PP7631573,Recharge_Bills,Mobile Recharge,Success,Success,19-07-2026
2096,RCG_U8P7A0DAV9AQE,74.79,PP4792929,Recharge_Bills,DTH,Success,Success,19-07-2026
2097,RCG_5VGQEK1RLLC47,1127.02,PP5759364,Recharge_Bills,nan,Success,Success,19-07-2026
2098,RCG_CHVDSADTO9L9U,962.25,PP4201913,Recharge_Bills,Cable TV,Success,Success,19-07-2026
2099,RCG_NYKTGLNZIYIQL,1446.10,PP5951380,Recharge_Bills,nan,Success,Success,19-07-2026

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2100 entries, 0 to 2099
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction ID  2038 non-null   str
 1   Amount          2038 non-null   float64
 2   User ID         2038 non-null   str
 3   Service         2038 non-null   str
 4   Service Type    2040 non-null   str
 5   Payment_Status  2038 non-null   str
 6   Reason          2038 non-null   str
 7   Date            2038 non-null   str
dtypes: float64(1), str(7)
memory usage: 131.4 KB

In [6]:
df.dtypes

Transaction ID        str
Amount            float64
User ID               str
Service               str
Service Type          str
Payment_Status        str
Reason                str
Date                  str
dtype: object

In [7]:
df.isnull().sum()

Transaction ID    62
Amount            62
User ID           62
Service           62
Service Type      60
Payment_Status    62
Reason            62
Date              62
dtype: int64

In [8]:
(df.isnull().sum()/len(df))*100

Transaction ID    2.952381
Amount            2.952381
User ID           2.952381
Service           2.952381
Service Type      2.857143
Payment_Status    2.952381
Reason            2.952381
Date              2.952381
dtype: float64

In [9]:
df[df.duplicated()]

,Transaction ID,Amount,User ID,Service,Service Type,Payment_Status,Reason,Date
2004,RCG_8FC81F79AF71,1153.77,PP0023767,Recharge_Bills,FASTag Recharge,Failed,Insufficient amount,12-09-2024
2005,RCG_886CC52B76CF,1834.01,PP0026526,Recharge_Bills,Mobile Recharge,Successful,Successful,31-10-2024
2006,RCG_2303ADE13226,1805.31,PP1080466,Recharge_Bills,FASTag Recharge,Successful,Successful,21-08-2024
2010,RCG_D6978500787F,1996.22,PP0038373,Recharge_Bills,DTH,Successful,Successful,18-04-2024
2011,RCG_8A268BE94630,1074.97,PP1071612,Recharge_Bills,Mobile Recharge,Successful,Successful,10-03-2024
2013,RCG_797E30C3AC3F,1686.69,PP1070709,Recharge_Bills,Cable TV,Successful,Successful,03-05-2024
2015,RCG_832CA9F0E0CF,104.71,PP0047257,Recharge_Bills,DTH,Successful,Successful,18-09-2024
2023,RCG_135F29A87E05,1691.94,PP0001171,Recharge_Bills,FASTag Recharge,Successful,Successful,14-10-2024
2024,RCG_647B8869E9A9,1511.13,PP1084469,Recharge_Bills,Cable TV,Successful,Successful,07-06-2024
2025,RCG_8060A6901111,1647.70,PP1055402,Recharge_Bills,DTH,Successful,Successful,28-06-2024
2027,RCG_CCDB313C05A3,400.04,PP1059508,Recharge_Bills,FASTag Recharge,Successful,Successful,28-09-2024
2031,RCG_C653F0A93B22,1036.17,PP1052255,Recharge_Bills,DTH,Successful,Successful,15-09-2024
2037,RCG_12C206213732,321.52,PP0013038,Recharge_Bills,Mobile Recharge,Successful,Successful,05-08-2024
2038,RCG_6F54FF2EC057,1323.29,PP0033071,Recharge_Bills,Cable TV,Successful,Successful,30-05-2024
2039,RCG_D087A1457D9E,1758.66,PP1060780,Recharge_Bills,FASTag Recharge,Successful,Successful,03-07-2024
2045,RCG_3EE49C1D52E9,290.81,PP0006365,Recharge_Bills,FASTag Recharge,Successful,Successful,16-05-2024
2046,RCG_33F0CC673F58,1401.63,PP1077510,Recharge_Bills,DTH,Successful,Successful,04-01-2024
2048,RCG_E392F6AA90F4,506.60,PP1052014,Recharge_Bills,Mobile Recharge,Successful,Successful,20-03-2024
2049,RCG_1F3A314FA40A,1653.27,PP0002097,Recharge_Bills,FASTag Recharge,Successful,Successful,16-09-2024

In [10]:
df.duplicated().sum()

np.int64(19)

# data cleaning process

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df[df.duplicated()]

Empty DataFrame
Columns: [Transaction ID, Amount, User ID, Service, Service Type, Payment_Status, Reason, Date]
Index: []

In [14]:
df.nunique()

Transaction ID    1995
Amount            1984
User ID           1977
Service              1
Service Type         9
Payment_Status       3
Reason               7
Date               419
dtype: int64

In [15]:
for col in df.columns:
    print(col)
    print(df[col].unique())
    print("-"*40)

Transaction ID
<StringArray>
[ 'RCG_0C338474B366',  'RCG_6B3B86B07A76',  'RCG_767822392A0E',
  'RCG_527E6AC74B11',  'RCG_6B50A8C694E1',  'RCG_E63DCBDBB8C9',
  'RCG_DD16B3117FB9',  'RCG_654D31ECCDC2',  'RCG_6C53A7808151',
  'RCG_92AE572161FA',
 ...
 'RCG_JMOODWA21F0G8', 'RCG_NAPDSELUP020L', 'RCG_B8JXAPC7P3YGM',
 'RCG_NE78S75DCXO5C', 'RCG_WFRGBYK1YMXH6', 'RCG_408JTREE6EHCX',
 'RCG_U8P7A0DAV9AQE', 'RCG_5VGQEK1RLLC47', 'RCG_CHVDSADTO9L9U',
 'RCG_NYKTGLNZIYIQL']
Length: 1996, dtype: str
----------------------------------------
Amount
[ 926.59 1211.64  746.27 ... 1127.02  962.25 1446.1 ]
----------------------------------------
User ID
<StringArray>
['PP0021371', 'PP0002388', 'PP1101831', 'PP0033099', 'PP1059869', 'PP1093720',
 'PP1067328', 'PP0041770', 'PP0017979', 'PP1085390',
 ...
 'PP1305770', 'PP1773627', 'PP8350965', 'PP7929419', 'PP3926110', 'PP7631573',
 'PP4792929', 'PP5759364', 'PP4201913', 'PP5951380']
Length: 1978, dtype: str
----------------------------------------
Service
<StringArray>
['Recharge_Bills', nan]
Length: 2, dtype: str
----------------------------------------
Service Type
<StringArray>
[ 'FASTag Recharge',              'DTH',         'Cable TV',
  'Mobile Recharge',                nan, 'FASTag Recharge ',
 'Mobile Recharge ',             'DTH ',        'Cable TV ',
             'nan ']
Length: 10, dtype: str
----------------------------------------
Payment_Status
<StringArray>
['Successful', 'Failed', nan, 'Success']
Length: 4, dtype: str
----------------------------------------
Reason
<StringArray>
[          'Successful',                    nan,  'Insufficient amount',
            'Wrong PIN',         'Server error',              'Success',
 'Insufficient Balance',         'Server Error']
Length: 8, dtype: str
----------------------------------------
Date
<StringArray>
['09-06-2024', '04-08-2024', '19-02-2024', '22-12-2024', '07-09-2024',
 '25-07-2024', '06-08-2024', '23-04-2024', '25-06-2024', '20-11-2024',
 ...
 '2024/03/11', '2024/03/14', '2024/07/14', '2024/12/28', '21-06-2024',
 '2024/01/28', '2024/12/04', '2024/09/14', '2024/06/04', '19-07-2026']
Length: 420, dtype: str
----------------------------------------

# remove extra spaces

In [16]:
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

# Standardize Column Names

In [17]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")

In [18]:
df.head()

,transaction_id,amount,user_id,service,service_type,payment_status,reason,date
0,RCG_0C338474B366,926.59,PP0021371,Recharge_Bills,FASTag Recharge,Successful,Successful,09-06-2024
1,RCG_6B3B86B07A76,1211.64,PP0002388,Recharge_Bills,DTH,Successful,Successful,04-08-2024
2,RCG_767822392A0E,746.27,PP1101831,Recharge_Bills,Cable TV,Successful,Successful,19-02-2024
3,RCG_527E6AC74B11,1319.89,PP0033099,NaN,Mobile Recharge,Successful,Successful,22-12-2024
4,RCG_6B50A8C694E1,112.44,PP1059869,Recharge_Bills,Cable TV,Successful,Successful,07-09-2024

# Fill Missing Values

In [19]:
df["service"] = df["service"].fillna("Recharge_Bills")

In [20]:
df["service_type"] = df["service_type"].fillna(df["service_type"].mode()[0])

In [21]:
text_columns = ["service", "service_type"]

for col in text_columns:
    df[col] = df[col].str.title()

In [22]:
df["user_id"] = df["user_id"].fillna("Unknown")

In [23]:
df["amount"] = df["amount"].fillna(df["amount"].median())

In [24]:
df["payment_status"] = df["payment_status"].fillna("Unknown")

In [25]:
df["reason"] = df["reason"].fillna("Unknown")

In [26]:
df["date"] = pd.to_datetime(df["date"], format="mixed", dayfirst=True)
df["date"] = df["date"].dt.strftime("%d-%m-%Y")

In [27]:
df.describe()

            amount
count  2081.000000
mean   1008.105656
std     566.299951
min      20.430000
25%     517.980000
50%    1014.300000
75%    1497.370000
max    1997.400000

In [28]:
Q1 = df["amount"].quantile(0.25)
Q3 = df["amount"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

df[(df["amount"] < lower) | (df["amount"] > upper)]

Empty DataFrame
Columns: [transaction_id, amount, user_id, service, service_type, payment_status, reason, date]
Index: []

In [29]:
df[df["amount"] < 0]

Empty DataFrame
Columns: [transaction_id, amount, user_id, service, service_type, payment_status, reason, date]
Index: []

In [30]:
df.dtypes

transaction_id        str
amount            float64
user_id               str
service               str
service_type          str
payment_status        str
reason                str
date                  str
dtype: object

# convert data type

In [31]:
df["transaction_id"] = df["transaction_id"].astype("string")
df["user_id"] = df["user_id"].astype("string")
df["service"] = df["service"].astype("category")
df["service_type"] = df["service_type"].astype("category")
df["payment_status"] = df["payment_status"].astype("category")
df["reason"] = df["reason"].astype("category")
df["date"] = pd.to_datetime(df["date"], format="mixed", dayfirst=True)

In [32]:
df.dtypes

transaction_id            string
amount                   float64
user_id                   string
service                 category
service_type            category
payment_status          category
reason                  category
date              datetime64[us]
dtype: object

In [33]:
df.isnull().sum()

transaction_id    62
amount             0
user_id            0
service            0
service_type       0
payment_status     0
reason             0
date              62
dtype: int64

In [34]:
df[df["transaction_id"].isnull()]

,transaction_id,amount,user_id,service,service_type,payment_status,reason,date
146,<NA>,202.49,PP0027820,Recharge_Bills,Cable Tv,Successful,Successful,2024-10-20
147,<NA>,1099.46,PP1093328,Recharge_Bills,Dth,Successful,Successful,2024-05-17
170,<NA>,1829.32,PP0041863,Recharge_Bills,Dth,Successful,Successful,2024-02-26
187,<NA>,1495.97,PP0008364,Recharge_Bills,Cable Tv,Successful,Successful,2024-12-09
189,<NA>,1630.64,PP0010820,Recharge_Bills,Mobile Recharge,Successful,Successful,2024-06-28
...,...,...,...,...,...,...,...,...
1917,<NA>,1457.90,PP1055454,Recharge_Bills,Fastag Recharge,Successful,Successful,2024-09-12
2001,<NA>,406.00,PP0015044,Recharge_Bills,Fastag Recharge,Successful,Successful,2024-10-31
2017,<NA>,1553.81,PP0002498,Recharge_Bills,Cable Tv,Successful,Successful,2024-08-25
2030,<NA>,1487.70,PP1056529,Recharge_Bills,Cable Tv,Successful,Successful,2024-08-27
2033,<NA>,1505.16,PP0049162,Recharge_Bills,Dth,Successful,Successful,2024-03-31

In [35]:
df[df["date"].isnull()]

,transaction_id,amount,user_id,service,service_type,payment_status,reason,date
62,RCG_AEFC6F654A71,438.05,PP1078041,Recharge_Bills,Cable Tv,Successful,Successful,NaT
149,RCG_4EA8EADE1F10,396.13,PP1055991,Recharge_Bills,Mobile Recharge,Successful,Successful,NaT
175,RCG_0B23FB3B32CE,1944.22,PP0033237,Recharge_Bills,Cable Tv,Successful,Successful,NaT
235,RCG_6C8B9232CDED,1649.79,PP1098558,Recharge_Bills,Cable Tv,Successful,Successful,NaT
240,RCG_523BC185158C,1760.81,PP1099957,Recharge_Bills,Fastag Recharge,Successful,Successful,NaT
...,...,...,...,...,...,...,...,...
1887,RCG_2CFEE82F0E81,1135.40,PP1060458,Recharge_Bills,Dth,Successful,Successful,NaT
1905,RCG_FB4707F833DB,1393.91,PP1073325,Recharge_Bills,Cable Tv,Successful,Successful,NaT
1980,RCG_32A32F4235EB,1014.30,PP1087651,Recharge_Bills,Fastag Recharge,Successful,Successful,NaT
1983,RCG_982C2F734C35,65.86,PP1098083,Recharge_Bills,Mobile Recharge,Successful,Successful,NaT
2019,RCG_1E74F6312A77,984.10,Unknown,Recharge_Bills,Cable Tv,Successful,Successful,NaT

In [36]:
df.dropna(subset=["transaction_id", "date"], inplace=True)

In [37]:
df.isnull().sum()

transaction_id    0
amount            0
user_id           0
service           0
service_type      0
payment_status    0
reason            0
date              0
dtype: int64

In [38]:
df.to_csv("../Data/clean_data/Cleaned.csv", index=False)

# Connect Python With Jupyter notebook then load data

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyodbc in C:\Users\navdh\AppData\Roaming\Python\Python314\site-packages (5.3.0)

In [41]:
import pyodbc
import pandas as pd

['SQL Server', 'ODBC Driver 17 for SQL Server', 'ODBC Driver 18 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

# code for connect python with sql server

Connected Successfully

# Create database in Sql Server

Database Created Successfully

# connect python with PhonePeDB

Connected to PhonePeDB

# create table in PhonePeDB with name Transactions

Table Created Successfully

Index(['transaction_id', 'amount', 'user_id', 'service', 'service_type',
       'payment_status', 'reason', 'date'],
      dtype='str')

In [49]:
df.dtypes

transaction_id        str
amount            float64
user_id               str
service               str
service_type          str
payment_status        str
reason                str
date                  str
dtype: object

In [50]:
df["transaction_id"] = df["transaction_id"].astype("string")
df["user_id"] = df["user_id"].astype("string")
df["service"] = df["service"].astype("category")
df["service_type"] = df["service_type"].astype("category")
df["payment_status"] = df["payment_status"].astype("category")
df["reason"] = df["reason"].astype("category")
df["date"] = pd.to_datetime(df["date"], format="mixed", dayfirst=True)

In [51]:
df.dtypes

transaction_id            string
amount                   float64
user_id                   string
service                 category
service_type            category
payment_status          category
reason                  category
date              datetime64[us]
dtype: object

# Load data into in Transactions Tbale